### ISSUE TITLE
Vectorized RS.* wrappers

### ISSUE THREAD

**Issue by jangorecki** [s-u/RSclient#1]
I've made few wrappers on `RS.*` which accept list of `rsc` (referred later as `rscl`).
Usually it is only something like `rscl.* = function(...) sapply(rscl, RS.*, ...)`.
Additionally there are some predefined defaults for arguments. Some other minor adjustments, like `rscl.collect` uses `try()` by default, to not interrupt collection from all Rserve machines after first error.

There are some extra wrappers:
`rscl.require` - require multiple packages on multiple nodes at once.
`rscl.ls.str` - capture output of `ls.str(envir=.GlobalEnv)` from multiple nodes and prints locally

All my codes related to RSclient wrappers can be found in [rscl.R](https://gitlab.com/jangorecki/big.data.table/blob/master/R/rscl.R). Should not have any other dependency.

Are you interested in contribution? so such utilities would be part of RSclient, or you prefer to keep RSclient as a simple core interface and let user to write their wrappers.
Example use case of `rscl.*`: http://stackoverflow.com/a/35066323/2490497

Edit: just added `parallel` arg to `rscl.eval` so it can also auto collect results after sending with `wait=FALSE`.

**Comment by s-u** [comment]
I would suggest creating another package. RSclient is already messed up by having two different client implementations (see `RS.connect` vs `RSconnect`) so it's probably easier if you just create another package (`rsc.tools`?).

**Comment by jangorecki** [comment]
Just for future reference, all mentioned wrappers landed in https://github.com/jangorecki/big.data.table package.
