### ISSUE TITLE
Missing -lcrypto

### ISSUE THREAD

**Issue by dmacks** [s-u/RSclient#4]
rsclient directly uses libcrypto symbols, such as ERR_get_error, but does not link directly against libcrypto. The symbols "probably always" get resolved at runtime via R itself that has already loaded libcrypto, but it's fragile to rely on others' linking to resolve one's own symbol use. It would be safer to have rsclient's Makevars pass -lcrypto (as well as the existing -lssl).

**Comment by s-u** [comment]
Looks like this has been done in 772f133
